Validatesの設定
Masato-Akizaki/task_app pull request #7
Opened 2018-08-24 09:35 UTC by Masato-Akizaki

タスク名の登録を必須項目にし、viewでエラーメッセージの表示を追加しました。
また、文字数制限も仮で設定しました。

現段階では、カラムが2つしかない為、今後カラムを追加ごとにバリデーションの設定をしていきます。

また、モデルのテストを作成しパスしました。

2018-09-10 08:23 UTC, takatoshi-maeda approved these changes

2018-09-10 08:24 UTC, takatoshi-maeda requested changes

2018-09-10 08:24 UTC, takatoshi-maeda commented on app/views/shared/_error_messages.html.erb
> +<% if @task.errors.any? %>
partialで暗黙的にインスタンス変数を呼び出すのは基本よくありません。呼び出す時に、内部構造を知っている必要があるためです。引数の渡し方をローカル変数で渡すようにしてください

2018-09-13 02:22 UTC, Masato-Akizaki commented on app/views/shared/_error_messages.html.erb
> +<% if @task.errors.any? %>
下記のように変更しました
6877db2

（`button_text`も後の変更で引数として渡しています。）

2018-09-14 04:59 UTC, Jun0kada commented
LGTMです〜
mergeしちゃってください！

2018-09-14 05:08 UTC, merged