終了期限の追加
Masato-Akizaki/task_app pull request #8
Opened 2018-08-27 10:03 UTC by Masato-Akizaki

DBに期限日カラムを追加し、入力フォームと一覧ページ、詳細ページのビューを編集しました。
ソートボタンを追加し、作成順と期限日順でソートできるようにしました。
また、specも拡充し、各パターンの表示順をテストしました。

2018-09-10 08:27 UTC, takatoshi-maeda requested changes

2018-09-10 08:27 UTC, TakatoshiMaeda commented on app/controllers/tasks_controller.rb
> +    @tasks = Task.all.order(sort_column + ' ' + sort_direction)
Hashで受け渡す方法があるはずです。確認してみてください。

2018-09-14 03:51 UTC, Masato-Akizaki commented on app/controllers/tasks_controller.rb
> +    @tasks = Task.all.order(sort_column + ' ' + sort_direction)
下記のように変更しました
a9c20ee

2018-09-14 05:04 UTC, Jun0kada commented
先にコンフリクト直してみてください！

2018-09-14 06:47 UTC, merged